---
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:
  name: My Home
  temperature_unit: C
  unit_system: metric
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  time_zone: !secret time_zone
  external_url: !secret external_url
  internal_url: "http://home-assistant.home-assistant.svc.cluster.local:8123"

sun:
system_health:

http:
  ip_ban_enabled: false
  login_attempts_threshold: 5
  use_x_forwarded_for: true
  trusted_proxies:
    - "10.244.0.0/16"  # pod subnet
    - "10.96.0.0/12"   # service subnet

sonos:
  media_player:
    advertise_addr: 10.22.27.251
    hosts:
      - !secret sonos_play_5
      - !secret sonos_soundbar
      - !secret sonos_subwoofer

zha:
  database_path: /config/zigbee.db
  enable_quirks: true
  # custom_quirks_path: /config/zhaquirks
