kuche_pflanzenlicht:
  name: "Pflanzenlicht (Küche)"
  icon: mdi:home-clock
  monday:
    - from: "09:00:00"
      to: "13:00:00"
    - from: "15:00:00"
      to: "20:00:00"
  tuesday:
    - from: "09:00:00"
      to: "13:00:00"
    - from: "15:00:00"
      to: "20:00:00"
  wednesday:
    - from: "09:00:00"
      to: "13:00:00"
    - from: "15:00:00"
      to: "20:00:00"
  thursday:
    - from: "09:00:00"
      to: "13:00:00"
    - from: "15:00:00"
      to: "20:00:00"
  friday:
    - from: "09:00:00"
      to: "13:00:00"
    - from: "15:00:00"
      to: "20:00:00"
  saturday:
    - from: "09:00:00"
      to: "13:00:00"
    - from: "15:00:00"
      to: "20:00:00"
  sunday:
    - from: "09:00:00"
      to: "13:00:00"
    - from: "15:00:00"
      to: "20:00:00"

wohnzimmer_pflanzenlicht:
  name: "Pflanzenlicht (Wohnzimmer)"
  icon: mdi:home-clock
  monday:
    - from: "08:00:00"
      to: "11:00:00"
    - from: "16:00:00"
      to: "18:00:00"
  tuesday:
    - from: "08:00:00"
      to: "11:00:00"
    - from: "16:00:00"
      to: "18:00:00"
  wednesday:
    - from: "08:00:00"
      to: "11:00:00"
    - from: "16:00:00"
      to: "18:00:00"
  thursday:
    - from: "08:00:00"
      to: "11:00:00"
    - from: "16:00:00"
      to: "18:00:00"
  friday:
    - from: "08:00:00"
      to: "11:00:00"
    - from: "16:00:00"
      to: "18:00:00"
  saturday:
    - from: "08:00:00"
      to: "11:00:00"
    - from: "16:00:00"
      to: "18:00:00"
  sunday:
    - from: "08:00:00"
      to: "11:00:00"
    - from: "16:00:00"
      to: "18:00:00"

wohnzimmer_pflanzenlicht_wand:
  name: "Pflanzenlicht (Wohnzimmer, Wand)"
  icon: mdi:home-clock
  monday:
    - from: "12:00:00"
      to: "15:00:00"
  tuesday:
    - from: "12:00:00"
      to: "15:00:00"
  wednesday:
    - from: "12:00:00"
      to: "15:00:00"
  thursday:
    - from: "12:00:00"
      to: "15:00:00"
  friday:
    - from: "12:00:00"
      to: "15:00:00"
  saturday:
    - from: "12:00:00"
      to: "15:00:00"
  sunday:
    - from: "12:00:00"
      to: "15:00:00"

wohnzimmer_pflanzenlicht_fenster:
  name: "Pflanzenlicht (Wohnzimmer Fenster)"
  icon: mdi:home-clock
  monday:
    - from: "08:00:00"
      to: "10:00:00"
    - from: "18:00:00"
      to: "20:00:00"
  tuesday:
    - from: "08:00:00"
      to: "10:00:00"
    - from: "18:00:00"
      to: "20:00:00"
  wednesday:
    - from: "08:00:00"
      to: "10:00:00"
    - from: "18:00:00"
      to: "20:00:00"
  thursday:
    - from: "08:00:00"
      to: "10:00:00"
    - from: "18:00:00"
      to: "20:00:00"
  friday:
    - from: "08:00:00"
      to: "10:00:00"
    - from: "18:00:00"
      to: "20:00:00"
  saturday:
    - from: "08:00:00"
      to: "10:00:00"
    - from: "18:00:00"
      to: "20:00:00"
  sunday:
    - from: "08:00:00"
      to: "10:00:00"
    - from: "18:00:00"
      to: "20:00:00"
