---
# Use this file to store secrets like usernames and passwords.
# Learn more at https://www.home-assistant.io/docs/configuration/secrets/

# The existing file is encrypted. See git-crypt for more information, or e.g.
# https://dev.to/heroku/how-to-manage-your-secrets-with-git-crypt-56ih

some_password: welcome
