# https://metallb.universe.tf/configuration/
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: dynamic
  namespace: metallb-system
spec:
  addresses:
    - 10.30.200.50-10.30.200.250
