# https://metallb.universe.tf/configuration/
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: static
  namespace: metallb-system
spec:
  addresses:
    - 10.30.200.1-10.30.200.49
  autoAssign: false
