---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: home-assistant

resources:
  - ../base

patches:
  - target:
      version: v1
      kind: Ingress
      name: home-assistant
    patch: |-
      - op: replace
        path: /spec/ingressClassName
        value: nginx
#      - op: replace
#        path: /spec/tls/0/hosts/0
#        value: home-assistant.fritz.box
#      - op: replace
#        path: /spec/tls/0/secretName
#        value: example.com-production-secret
#      - op: replace
#        path: /spec/rules/0/host
#        value: example.com
