# See: https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/pihole.md
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-dns

images:
  - name: registry.k8s.io/external-dns/external-dns
    newTag: v0.14.0

# kubectl create secret generic -n external-dns pihole-password --from-literal EXTERNAL_DNS_PIHOLE_PASSWORD=supersecret

resources:
  - namespace.yaml
  - install.yaml
