---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: home-assistant
    version: "2024.2.2"
  name: home-assistant
  namespace: home-assistant
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
        version: "2024.2.2"
    spec:
      containers:
      - name: app
        image: "ghcr.io/home-assistant/home-assistant:2024.2"
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: false
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
        envFrom:
          - configMapRef:
              name: home-assistant-config
        ports:
          - name: http
            containerPort: 8123
            protocol: TCP
          - name: udp-ssdp
            containerPort: 1900
            protocol: UDP
          - name: udp-mdns
            containerPort: 5353
            protocol: UDP
          - name: udp-unicast
            containerPort: 5683
            protocol: UDP
          - name: udp-homekit
            containerPort: 51827
            protocol: UDP
        resources:
          limits:
            cpu: 2
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 0
          failureThreshold: 3
          timeoutSeconds: 1
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 0
          failureThreshold: 3
          timeoutSeconds: 1
          periodSeconds: 10
        startupProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 0
          failureThreshold: 30
          timeoutSeconds: 1
          periodSeconds: 5
        volumeMounts:
          - name: ha-config-root
            mountPath: /config
          - name: home-assistant-config-files
            mountPath: /config/configuration.yaml
            subPath: configuration.yaml
          - name: home-assistant-config-files
            mountPath: /config/automations.yaml
            subPath: automations.yaml
          - name: home-assistant-config-files
            mountPath: /config/scenes.yaml
            subPath: scenes.yaml
          - name: home-assistant-config-files
            mountPath: /config/scripts.yaml
            subPath: scripts.yaml
          - name: home-assistant-secrets
            mountPath: /config/secrets.yaml
            subPath: secrets.yaml
      restartPolicy: Always
      volumes:
        - name: ha-config-root
          persistentVolumeClaim:
            claimName: home-assistant-config-root
        - name: home-assistant-config-files
          configMap:
            name: home-assistant-config-files
            optional: true
        - name: home-assistant-secrets
          secret:
            secretName: home-assistant-secrets
            optional: true
