---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: home-assistant

images:
  - name: ghcr.io/home-assistant/home-assistant
    newTag: "2024.2"

resources:
  - namespace.yaml
  - mem-limit.yaml
  - persistent-volume-claim.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: home-assistant
  app: home-assistant

configMapGenerator:
  - name: home-assistant-config
    namespace: home-assistant
    literals:
      - TZ="UTC"
