---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: home-assistant

images:
  - name: ghcr.io/home-assistant/home-assistant
    newTag: "2025.10"

resources:
  - namespace.yaml
  - mem-limit.yaml
  - persistent-volume-claim.yaml
  - deployment.yaml
  - services.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: home-assistant
  app: home-assistant

configMapGenerator:
  - name: home-assistant-config
    namespace: home-assistant
    literals:
      - TZ="Europe/Berlin"
      - HASS_HOST="10.22.27.251"
  - name: home-assistant-config-files
    namespace: home-assistant
    files:
      - configs/configuration.yaml
      - configs/scenes.yaml
      - configs/scripts.yaml
      - configs/automations.yaml
      - configs/schedules.yaml

secretGenerator:
- name: home-assistant-secrets
  files:
    - configs/secrets.yaml
