---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: home-assistant-config-root
  namespace: home-assistant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
