---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mosquitto

images:
  - name: eclipse-mosquitto
    newTag: "2.0.18-openssl"

resources:
  - namespace.yaml
  - persistent-volume-claim.yaml
  - deployment.yaml
  - services.yaml

commonLabels:
  app.kubernetes.io/name: mosquitto
  app: mosquitto


configMapGenerator:
  - name: mosquitto-config
    namespace: mosquitto
    files:
      - mosquitto.conf
